# Generated by Django 6.0.6 on 2026-07-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_stripe_payment_intent_id_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='pricing_mode',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('on_request', 'On Request')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('physical', 'Physical'), ('service', 'Service')], default='physical', max_length=20),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
