# Generated by Django 6.0.7 on 2026-07-11 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_bankaccount_alter_order_status_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default', '-id'], 'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرسها'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'دستهبندی', 'verbose_name_plural': 'دستهبندیها'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارشها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='quoterequest',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'درخواست قیمت', 'verbose_name_plural': 'درخواستهای قیمت'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'دیدگاه', 'verbose_name_plural': 'دیدگاهها'},
        ),
    ]
